### ISSUE TITLE
Elaborar Diagrama de Pacotes

### ISSUE THREAD

**Issue by CarolinaBarb** [UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning#18]
### Resumo

Desenvolver artefato Diagrama de Pacotes

### Tarefas

- [ ] Estudar [material disponibilizado no moodle](https://unbbr-my.sharepoint.com/personal/mileneserrano_unb_br/_layouts/15/stream.aspx?id=%2Fpersonal%2Fmileneserrano%5Funb%5Fbr%2FDocuments%2FArqDSW%20%2D%20V%C3%ADdeosOriginais%2F05g%20%2D%20VideoAula%20%2D%20DSW%2DModelagem%20%2D%20Pacotes%2Emp4&ga=1) 
- [ ] Desenvolver o artefato voltado para o projeto da disciplina.

### Critérios de Aceitação

- [ ] O artefato deve compor a documentação da equipe junto com seu versionamento e contribuições da equipe.
- [ ] O artefato deve seguir o template pré-definido pela equipe.
- [ ] O link do documento deve estar disponível na issue.

### Código de Conduta

- [X] Concordo em seguir o Código de Conduta deste projeto

**Comment by MatheusPerillo** [comment]
link do diagrama: [diagrama de pacotes](https://lucid.app/lucidchart/04e99123-87c7-4792-8e31-4097a29222a1/edit?invitationId=inv_e46685ce-c7ef-437b-bd01-5d1c46198e48&page=0_0#)

**Comment by The-Boss-Nina** [comment]
Durante a apresentação do Módulo 2, foi notado pela professora Milene, que apresentavam nomenclatura equivocada, com letra maiúscula em vez de minúscula. Segue abaixo a atualização do diagrama com as correções.

![Diagrama em branco - Página 1](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/58699832/fcfc4df1-74cd-4657-b58e-4c1a9a9e1cd6)

**Comment by The-Boss-Nina** [comment]
Correção da legenda.

![Diagrama em branco - Página 2](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/58699832/8639b925-11f9-48ca-b663-44d2004cadac)
