### ISSUE TITLE
Elaborar Diagrama de Classes

### ISSUE THREAD

**Issue by JuliaSSouza** [UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning#19]
### Resumo

Desenvolver artefato de diagrama de classes

### Tarefas

**Tarefas**

- [ ] Estudar [material disponibilizado no moodle](https://aprender3.unb.br/course/view.php?id=22090&section=3) sobre o artefato. 
- [ ] Desenvolver o artefato voltado para o projeto da disciplina.

### Critérios de Aceitação

**Critérios de aceitação**

- [ ] O artefato deve compor a documentação da equipe junto com seu versionamento e contribuições da equipe.
- [ ] O artefato deve seguir o template pré-definido pela equipe.
- [ ] O link do documento deve estar disponível na issue.

### Código de Conduta

- [X] Concordo em seguir o Código de Conduta deste projeto

**Comment by heylisten64** [comment]
![image](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/43069991/4907a1dc-8fa4-436e-a464-c187f7e5bc49)
rascunhei esse diagrama de classes aqui, mas durante nossa reunião pra desenvolver o diagrama achamos necessário ter uma reunião pra definir certinho o escopo do projeto para então refazermos
