### ISSUE TITLE
Elaborar Rich Picture

### ISSUE THREAD

**Issue by heylisten64** [UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning#2]
Desenvolver artefato Rich Picture.

**Tarefas**

- [x] Estudar [material disponibilizado no moodle](https://unbbr-my.sharepoint.com/:v:/g/personal/mileneserrano_unb_br/EeS6ET8l1DVLuA5jsX_o54cBLXdCt4ZtcDNACgh_RQAVhw?e=j3GV2g&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopiedShareExpTreatment%2Eview) sobre o artefato. [Vídeo extra](https://www.youtube.com/watch?v=8ZH-NKqKF9A).
- [x] Desenvolver o artefato voltado para o projeto da disciplina.

**Critérios de aceitação**

- [x] O artefato deve compor a documentação da equipe junto com seu versionamento e contribuições de cada membro.
- [x] O artefato deve seguir o template pré-definido pela equipe.
- [x] O link do documento deve estar disponível na issue.

**Comment by JuliaSSouza** [comment]
Link do documento:  https://drive.google.com/file/d/11DFwUDcg6ApO2DkA-ddthu9pUXKD0yNE/view?usp=sharing

![image](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/43069991/46fe4076-974b-4943-99c3-f3407c2c89a5)

**Comment by heylisten64** [comment]
Baseado no das meninas propus algumas mudanças, mas que vamos alinhar na reunião hoje meio dia ainda, conforme os feedbacks coletados pela equipe.
![Sem título](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/43069991/5c893951-677a-4585-8a0a-40efbe91b113)

**Comment by CarolinaBarb** [comment]
A versão final do Rich Picture pode ser encontrada no link a seguir https://www.figma.com/file/Eeed2Wn1ljq9p1IfB1K4jt/Arquitetura-e-Desenho-de-Software---Rich-Picture?type=design&node-id=0-1&mode=design&t=GamOCclEeNkJmyL3-0
![image](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/98655636/3dee246e-8424-486d-b018-5ee86458341e)

**Comment by heylisten64** [comment]
vou documentar agora o artefato.

**Comment by heylisten64** [comment]
Propus uma mudanca para se adequar ao jeito como realizaram o rich picture que foi aprovada pela equipe. 
![image](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/43069991/a577055a-5827-429a-b5c1-bbf70a15d542)

**Comment by heylisten64** [comment]
https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/blob/main/docs/Base/1.4.DesignSprint/1.4.3.RichPicture.md
