### ISSUE TITLE
Elaborar Digrama de Sequência

### ISSUE THREAD

**Issue by CarolinaBarb** [UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning#20]
### Resumo

Desenvolver artefato Diagrama de Sequência

### Tarefas

- [x] Estudar [material disponibilizado no moodle](https://unbbr-my.sharepoint.com/personal/mileneserrano_unb_br/_layouts/15/stream.aspx?id=%2Fpersonal%2Fmileneserrano%5Funb%5Fbr%2FDocuments%2FArqDSW%20%2D%20V%C3%ADdeosOriginais%2F06a%20%2D%20VideoAula%20%2D%20DSW%2DModelagem%20%2D%20Sequencia%2Emp4&ga=1) 
- [x] Desenvolver o artefato voltado para o projeto da disciplina.

### Critérios de Aceitação

- [ ] O artefato deve compor a documentação da equipe junto com seu versionamento e contribuições da equipe.
- [x] O artefato deve seguir o template pré-definido pela equipe.
- [ ] O link do documento deve estar disponível na issue.

### Código de Conduta

- [X] Concordo em seguir o Código de Conduta deste projeto

**Comment by heylisten64** [comment]
diagrama feito, assim que chegar em casa hoje faço o documento pra pages 
![Sem título](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/43069991/c19983c8-f0d0-455d-ac61-1c344c90f60c)

**Comment by heylisten64** [comment]
tive alguns imprevistos, então a @The-Boss-Nina vai me ajudar na parte de explicar o diagrama elaborado

**Comment by The-Boss-Nina** [comment]
@heylisten64  a imagem do diagrama acima e as explicações dos tópicos relacionados foram adicionadas ao documento 'pages'.

**Comment by The-Boss-Nina** [comment]
Durante a aula do dia 05/07, foi notado pela professora Milene, que estava faltando cardinalidade no nosso diagrama. Segue abaixo a atualização do diagrama com as cardinalidades apontadas.

![Blank diagram](https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/assets/58699832/987a941b-f550-43ac-a712-79ff39695d7d)
