### ISSUE TITLE
Elaborar Notação BPMN

### ISSUE THREAD

**Issue by heylisten64** [UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning#4]
Desenvolver Notação BPMN.

**Tarefas**

- [x] Estudar [material disponibilizado no moodle](https://unbbr-my.sharepoint.com/:v:/g/personal/mileneserrano_unb_br/EU1pA17SX3VEttZ6KlARD_ABd-SNiJJ1AwODqrO9zEfQBw?e=vTxaUp) sobre a notação. [Vídeos extras 1-8](https://www.youtube.com/watch?v=_KdCwaOp7zE).
- [x] Desenvolver a notação voltado para o projeto da disciplina.

**Critérios de aceitação**

- [x] O trabalho desenvolvido deve compor a documentação da equipe junto com seu versionamento e contribuições de cada membro.
- [x] O link do documento deve estar disponível na issue.

**Comment by heylisten64** [comment]
@CarolinaBarb @FelipeDireito @FHansen98 também participam, mas devido limitações do github não podemos atribuir mais de 10 pessoas a issue.

**Comment by luishenrrique** [comment]
Conteúdo relacionado a notação BPMN está disponível no link a seguir https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/blob/main/docs/Base/1.2.ProcessosMetodologiasAbordagens.md
