### ISSUE TITLE
Elaborar Prototipo de Baixa Fidelidade

### ISSUE THREAD

**Issue by heylisten64** [UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning#6]
Desenvolver artefato Prototipo de Baixa Fidelidade.

**Tarefas**

- [x] Estudar [material disponibilizado no moodle](http://web.mit.edu/6.813/www/sp17/classes/08-prototyping/) sobre o artefato.
- [x] Desenvolver o artefato voltado para o projeto da disciplina.

**Critérios de aceitação**

- [x] O artefato deve compor a documentação da equipe junto com seu versionamento e contribuições da equipe.
- [x] O artefato deve seguir o template pré-definido pela equipe.
- [x] O link do documento deve estar disponível na issue.

**Comment by CarolinaBarb** [comment]
O protótipo de média fidelidade foi feito por @CarolinaBarb @JuliaSSouza  @luishenrrique @MatheusPerillo e está disponivel no link a seguir https://www.figma.com/file/DKVd7l0ODRA7lo3IimjKrS/prototipo?type=design&node-id=0-1&mode=design&t=Il33HdhPYBshObf4-0
