### ISSUE TITLE
Desenvolver Design Sprint

### ISSUE THREAD

**Issue by heylisten64** [UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning#7]
**Tarefas**

- [x] Estudar [material disponibilizado no moodle](https://unbbr-my.sharepoint.com/:v:/g/personal/mileneserrano_unb_br/EQtIkuASIUZOnKdMfHyHn0sB1jTKu3dIuSBBkwD_Z_JmDQ?e=YNP1Sm) sobre o Design Sprint.
- [x] Desenvolver o conteúdo orientado ao projeto da disciplina

**Critérios de aceitação**

- [x] O documento deve compor a pages com seu versionamento e contribuições de cada membro.
- [x] O link do documento deve estar disponível na issue.

**Comment by CarolinaBarb** [comment]
@CarolinaBarb @FelipeDireito @FHansen98 também participam, mas devido limitações do github não podemos atribuir mais de 10 pessoas a issue.

**Comment by luishenrrique** [comment]
Conteúdo relacionado a Desing Sprint está disponível no link a seguir https://unbarqdsw2024-1.github.io/2024.1_G6_My_LanguageLearning/#/Base/1.4.DesignSprint/1.4.1.Introducao
