### ISSUE TITLE
Elaborar Templates

### ISSUE THREAD

**Issue by heylisten64** [UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning#8]
Elaborar templates para ata de reunião, issues e artefatos na pages.

**Tarefas**
- [x] Elaborar template para ata de reunião.
- [x] Elaborar template para issues.
- [x] Elaborar template para os artefatos que compõem a pages.

**Critérios de Aceitação**

- [x] Os templates devem ser disponibilizados nesta issue, e nos principais canais de comunicação da equipe: teams e whatsapp.

**Comment by CarolinaBarb** [comment]
Fiquei responsável pelo template dos artefatos.
https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/blob/main/docs/Planejamento/ModeloDoc.md

**Comment by heylisten64** [comment]
feito o das issues! https://github.com/UnBArqDsw2024-1/2024.1_G6_My_LanguageLearning/blob/main/.github/ISSUE_TEMPLATE/issue.yml
